//AUTH
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"
export const REDIRECT = "REDIRECT"
export const LOGOUT_USER = "LOGOUT_USER"